version: "3.7"
volumes:
  snap-fifo:
  playlists:
services:
  mpd:
    build:
     context: .
     network: host
    image: .	
    container_name: mpd-main
    hostname: mpd
    env_file: .env # Add this line to specify the .env file
    volumes:
      - snap-fifo:/tmp
      - playlists:/.mpd/playlists
    ports:
      - 6690:6600
    restart: unless-stopped

