version: "3.7"
volumes:
  snap-fifo:
  playlists:
services:
  mpd:
    build:
     context: .
     network: host
    image: crowsbyte/mpd
    container_name: mpd-main
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /where/your/music/is/located:/var/lib/mpd/music
      - snap-fifo:/tmp
      - playlists:/.mpd/playlists
    ports:
      - 6600:6600
    restart: unless-stopped
