version: "3.9"

services:
  mpd:
    image: alpine-mpd
    privileged: true
    ports:
      - "6600:6600"
    volumes:
      - /mpd.conf:/etc/mpd.conf:ro
      - omv_music:/var/lib/mpd/music
      - playlistnf4:/var/lib/mpd/playlists
    devices:
      - /dev/snd:/dev/snd
    restart: always
    user: mpd

volumes:
  omv_music:
    external: true
  playlistnf4:
    external: true
