#version: "3.9"
services:
  mpd:
#    image: mini-mpd                          
    build: .
    privileged: true
    ports:
      - "6600:6600"
      - "8000:8000"
    volumes:
      - mpd_config:/var/lib/mpd/config
      - ./mpd.conf:/etc/mpd.conf:ro
  #    - nfs_music:/var/lib/mpd/music
 #     - nfs_playlist:/var/lib/mpd/playlist
    devices:
      - /dev/snd:/dev/snd
    restart: always
#    user: mpd
#    network_mode: host
    stdin_open: true   # enable interactive flag
    tty: true


  upmpdcli:
    image: giof71/upmpdcli:renderer
    container_name: upmpdcli-renderer
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - FRIENDLY_NAME=upmpd
    volumes:
      - ./cache:/cache
      - ./log:/log
      - ./config/additional-radio-list.txt:/user/config/additional-radio-list.txt:ro
    labels:
      - com.centurylinklabs.watchtower.e


volumes:
  mpd_config:
  nfs_music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.198,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/music"
  nfs_playlist:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.198,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/playlist"
